name: scan

on:
  push:
    branches: [ master ]

jobs:
  tern:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch tern
        run: git clone https://github.com/tern-tools/tern.git
      - name: Build tern container
        run: docker build . --file tern/Dockerfile --tag ternd
      - name: Run scan debian:buster
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cd tern
          ./docker_run.sh workdir ternd "report -f json -i debian:buster" > ${{ github.workspace }}/artifact/debian.txt
      - name: Run scan alpine 
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cd tern
          ./docker_run.sh workdir ternd "report -f json -i alpine:3.10.4" > ${{ github.workspace }}/artifact/alpine.txt
      - uses: actions/upload-artifact@v2
        with:
          name: tern-output
          path: ${{ github.workspace }}/artifact

